apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: my-spring-boot-app
  name: my-spring-boot-app
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-spring-boot-app
  template:
    metadata:
      labels:
        app: my-spring-boot-app
    spec:
      containers:
      - image: fuzzybsd/my-spring-boot-app:0.0.1
        name: my-spring-boot-app
