apiVersion: v1
kind: Service
metadata:
  labels:
    app: my-spring-boot-app
  name: my-spring-boot-app
spec:
  selector:
    app: my-spring-boot-app
  sessionAffinity: None
  type: NodePort
  ports:
  - name: port-for-app
    port: 8080
    protocol: TCP
    targetPort: 8080
  - name: port-for-metrics
    port: 9404
    protocol: TCP
    targetPort: 9404